---

  - name: Update the apt cache
    apt:
      update_cache: yes
      cache_valid_time: 3600
    become: yes

  - name: Install packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
        - software-properties-common
        - mariadb-server
        - mariadb-client
        - python3-mysqldb
