---
  - name: Include debian install
    include: install_debian.yml
    when: ansible_os_family == "Debian"

  - name: Include install tasks for RedHat
    include: install_redhat.yml
    when: ansible_os_family == "RedHat"

  - name: Disable network listening
    ini_file:
      path: /etc/my/cnf.d/server/cnf
      section: mysqld
      option: skip-networking
      value: ' # set by Ansible'
      no_extra_spaces: true
    notify:
      - restart_mariadb
    when: mariadb_allow_network is undefined or mariadb_allow_network is defined and not mariadb_allow_network

  - name: Set MariaDB tuning parameters
    ini_file:
      path: /etc/my.cnf.d/server.cnf
      section: mysqld
      option: "{{ item.key }}"
      value: "{{ item.value }}"
      no_extra_spaces: true
    notify:
      - restart_mariadb
    loop: "{{ mariadb_options | default({}) | dict2items }}"

  - name: Start and Enable MariaDB
    service:
      name: mysql
      state: started
      enabled: yes

  - name: Set root password
    mysql_user:
      name: root
      password: "{{ mariadb_root_pass }}"
    ignore_errors: yes #this task will fail everytime except the first.

  - name: Add users
    mysql_user:
      name: "{{ item.name }}"
      password: "{{ item.password | default(omit) }}"
      priv: "{{ item.priv | default(omit) }}"
      login_password: "{{ mariadb_root_pass }}"
    with_items: "{{ mariadb_users }}"

  - name: Add databases
    mysql_db:
      name: "{{ item.name }}"
      login_password: "{{ mariadb_root_pass }}"
    with_items: "{{ mariadb_databases }}"
